# Generated by Django 4.2.11 on 2024-05-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='opcoes_tamanho',
            field=models.CharField(blank=True, help_text='Separadas por vírgula', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(max_length=800),
        ),
    ]
