# Generated by Django 4.2.11 on 2024-05-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço de Marketing'),
    ]
 operations = []