# Generated by Django 4.2.11 on 2024-06-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
    ]
