# Generated by Django 4.2.11 on 2024-05-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
    ]
