# Generated by Django 4.2.11 on 2024-05-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20240513_2314'),
    ]

    operations = [
    ]
