# Generated by Django 4.2.11 on 2024-05-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_options_and_more'),
    ]

    operations = [
    ]
