# Generated by Django 4.2.11 on 2024-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='preco_marketing',
            field=models.FloatField(default=0.0),
        ),
    ]
