# Generated by Django 4.2.11 on 2024-05-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_preco_marketing_and_more'),
        ('produto', '0006_alter_variacao_preco_marketing'),
    ]

    operations = [
    ]
