# Generated by Django 4.2.11 on 2024-05-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20240529_1407'),
    ]

    operations = [
         migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=models.CASCADE, to='nome_do_app.Produto')),
                ('carrinho', models.ForeignKey(on_delete=models.CASCADE, to='nome_do_app.Carrinho')),
                # Outros campos conforme necessário
            ],
    ]
