# Generated by Django 4.2.11 on 2024-05-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20240529_1407'),
    ]

    operations = [
    ]
