# Generated by Django 4.2.11 on 2024-05-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_preco_marketing_and_more'),
        ('produto', '0007_merge_20240526_1538'),
    ]

    operations = [
    ]
