# Generated by Django 4.2.11 on 2024-06-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20240625_1700'),
    ]

    operations = [
    ]
